services:
    imcger.recenttopicsng.controller.page_controller:
        class: imcger\recenttopicsng\controller\page_controller
        arguments:
            - '@config'
            - '@template'
            - '@controller.helper'
            - '@language'
            - '@auth'
            - '@imcger.recenttopicsng.functions'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@imcger.recenttopicsng.controller_common'

    imcger.recenttopicsng.admin.controller:
        class: imcger\recenttopicsng\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@request'
            - '@dbal.conn'
            - '@ext.manager'
            - '@controller.helper'
            - '@imcger.recenttopicsng.controller_common'

    imcger.recenttopicsng.controller_common:
        class: imcger\recenttopicsng\controller\controller_common
        arguments:
            - '@user'
            - '@auth'
            - '@dbal.conn'

    imcger.recenttopicsng.functions:
        class: imcger\recenttopicsng\core\rtng_functions
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@language'
            - '@content.visibility'
            - '@dbal.conn'
            - '@dispatcher'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@imcger.recenttopicsng.controller_common'
            - '@?phpbb.collapsiblecategories.operator'

    imcger.recenttopicsng.main_listener:
        class: imcger\recenttopicsng\event\main_listener
        arguments:
            - '@imcger.recenttopicsng.functions'
            - '@template'
            - '@controller.helper'
            - '@language'
            - '@auth'
            - '@imcger.recenttopicsng.controller_common'
        tags:
            - { name: event.listener }

    imcger.recenttopicsng.acp_listener:
        class: imcger\recenttopicsng\event\acp_listener
        arguments:
            - '@template'
            - '@request'
            - '@imcger.recenttopicsng.controller_common'
        tags:
            - { name: event.listener }

    imcger.recenttopicsng.ucp_listener:
        class: imcger\recenttopicsng\event\ucp_listener
        arguments:
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dbal.conn'
            - '@imcger.recenttopicsng.controller_common'
        tags:
            - { name: event.listener }
